const money = (value) => `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
const rows = (items) => items.map((item) => `<tr><td><b>${esc(item.code)}</b> ${esc(item.concept)}</td><td>${money(item.amount)}</td></tr>`).join("");
const header = (company, label) => `<header class="doc-header"><div class="doc-logo" style="background:${esc(company.color)}">${company.logoData ? `<img src="${company.logoData}" alt="" />` : esc(company.name.slice(0, 2))}</div><div><h1>${esc(company.legalName || company.name)}</h1><p>RUC ${esc(company.ruc)} · ${esc(company.address)}</p><p>${esc(company.phone)} · ${esc(company.email)}</p></div><span class="doc-type">${label}</span></header>`;
const shell = (title, company, body) => `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;color:#1b1916;margin:0;background:#eee9e1}.sheet{width:210mm;min-height:297mm;margin:20px auto;background:#fff;padding:18mm;box-sizing:border-box}.doc-header{display:flex;gap:15px;align-items:center;border-bottom:2px solid #b68b2c;padding-bottom:15px}.doc-logo{width:64px;height:64px;border-radius:12px;color:#fff;display:grid;place-items:center;font-weight:bold;overflow:hidden}.doc-logo img{width:100%;height:100%;object-fit:contain;background:#fff}.doc-header h1{font:600 19px Georgia,serif;margin:0 0 6px}.doc-header p{font-size:10px;margin:3px 0;color:#625a53}.doc-type{margin-left:auto;background:#b68b2c;color:#fff;padding:10px 14px;border-radius:7px;font-size:10px;font-weight:bold}.doc-section{margin-top:20px}.doc-section h2{font:600 14px Georgia,serif;border-bottom:1px solid #ddd2c3;padding-bottom:7px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.fact{background:#f8f5ef;padding:9px;font-size:10px}.fact b{display:block;color:#967329;font-size:8px;text-transform:uppercase;margin-bottom:4px}table{width:100%;border-collapse:collapse;font-size:10px}td,th{padding:8px;border-bottom:1px solid #e6dfd6;text-align:left}td:last-child,th:last-child{text-align:right}.total{margin-top:18px;background:#b68b2c;color:#fff;padding:13px;display:flex;justify-content:space-between;font-weight:bold}.doc-note{font-size:10px;line-height:1.6;color:#655d55;margin-top:15px}.doc-footer{margin-top:70px;border-top:1px solid #ddd2c3;padding-top:12px;font-size:9px;color:#8a7c6c;display:flex;justify-content:space-between}@media print{body{background:white}.sheet{margin:0;box-shadow:none}} </style></head><body><article class="sheet">${header(company, label)}${body}<footer class="doc-footer"><span>Estudio Contable JK · Chile, Amarilis 00011</span><span>950 361 967 · contacto@estudiojk.com.pe</span></footer></article></body></html>`;

export function payrollDocument(company, payroll) { const body = `<section class="doc-section"><h2>Información del trabajador</h2><div class="facts"><div class="fact"><b>Trabajador</b>${esc(payroll.employee)}</div><div class="fact"><b>DNI</b>${esc(payroll.dni)}</div><div class="fact"><b>Periodo</b>${esc(payroll.period)}</div><div class="fact"><b>Fecha de ingreso</b>${esc(payroll.startDate)}</div><div class="fact"><b>Cargo</b>${esc(payroll.workerType)}</div><div class="fact"><b>Régimen</b>${esc(payroll.pension)}</div></div></section><section class="doc-section"><h2>Ingresos</h2><table><tr><th>Concepto</th><th>Importe</th></tr>${rows(payroll.incomes)}<tr><th>Total ingresos</th><th>${money(payroll.totalIncome)}</th></tr></table></section><section class="doc-section"><h2>Descuentos</h2><table><tr><th>Concepto</th><th>Importe</th></tr>${rows(payroll.discounts)}<tr><th>Total descuentos</th><th>${money(payroll.totalDiscounts)}</th></tr></table></section><div class="total"><span>NETO A PAGAR</span><span>${money(payroll.net)}</span></div><section class="doc-section"><h2>Aportes del empleador</h2><table><tr><th>Concepto</th><th>Importe</th></tr>${rows(payroll.employerContributions)}</table></section>`; return shell(`Boleta ${payroll.period}`, company, body); }
export function feeDocument(company, data) { const total = data.items.reduce((sum, item) => sum + Number(item.amount || 0), 0); const body = `<p class="doc-note" style="text-align:center;color:#b68b2c;font-weight:bold">“Año de la Esperanza y el Fortalecimiento de la Democracia”</p><p class="doc-note">Sr(a). ${esc(company.representative)}, representante de ${esc(company.name)}:<br><br>${esc(data.greeting || `Reciba nuestro cordial saludo. Por medio de la presente hacemos llegar el detalle de los servicios profesionales brindados por Estudio Contable JK.`)}</p><section class="doc-section"><h2>Detalle de servicios</h2><table><tr><th>Concepto</th><th>Importe</th></tr>${data.items.map((item) => `<tr><td>${esc(item.description || "Servicio profesional")}</td><td>${money(item.amount)}</td></tr>`).join("")}</table><div class="total"><span>TOTAL</span><span>${money(total)}</span></div></section>${data.observations ? `<p class="doc-note"><b>Observaciones:</b> ${esc(data.observations)}</p>` : ""}`; return shell(`Honorarios ${company.ruc}`, company, body); }
export function openPrint(html, filename) { const win = window.open("", "_blank", "width=900,height=900"); if (!win) return; win.document.write(html); win.document.close(); win.document.title = filename; setTimeout(() => win.print(), 450); }
export { money };
