const money = (value) => `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
const initials = (value) => String(value || "JK").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const hex = (value) => /^#[0-9a-f]{6}$/i.test(value || "") ? value : "#a77b25";
const rgb = (value) => { const clean = hex(value).slice(1); return [0, 2, 4].map((index) => Number.parseInt(clean.slice(index, index + 2), 16)); };
const darkText = (value) => { const [r, g, b] = rgb(value); return r * 0.299 + g * 0.587 + b * 0.114 > 165 ? "#1c1b18" : "#ffffff"; };
const shade = (value, amount = .9) => { const [r, g, b] = rgb(value); return `rgb(${Math.round(r * amount)}, ${Math.round(g * amount)}, ${Math.round(b * amount)})`; };
const rounded = (ctx, x, y, width, height, radius = 16) => { const r = Math.min(radius, width / 2, height / 2); ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + width, y, x + width, y + height, r); ctx.arcTo(x + width, y + height, x, y + height, r); ctx.arcTo(x, y + height, x, y, r); ctx.arcTo(x, y, x + width, y, r); ctx.closePath(); };
const text = (ctx, value, x, y, options = {}) => { ctx.fillStyle = options.color || "#25231f"; ctx.font = `${options.weight || 400} ${options.size || 22}px ${options.family || "Arial"}`; ctx.textAlign = options.align || "left"; ctx.textBaseline = options.baseline || "alphabetic"; ctx.fillText(String(value || ""), x, y); };
const wrap = (ctx, value, maxWidth) => { const words = String(value || "").split(/\s+/); const lines = []; let line = ""; words.forEach((word) => { const next = `${line} ${word}`.trim(); if (line && ctx.measureText(next).width > maxWidth) { lines.push(line); line = word; } else line = next; }); if (line) lines.push(line); return lines; };
const paragraph = (ctx, value, x, y, maxWidth, options = {}) => { ctx.font = `${options.weight || 400} ${options.size || 21}px ${options.family || "Arial"}`; const step = options.leading || Math.round((options.size || 21) * 1.45); wrap(ctx, value, maxWidth).forEach((line, index) => text(ctx, line, x, y + index * step, options)); return y + wrap(ctx, value, maxWidth).length * step; };
const line = (ctx, x1, y1, x2, y2, color = "#d8d1c6", width = 1) => { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.strokeStyle = color; ctx.lineWidth = width; ctx.stroke(); };
// A logo from Supabase Storage is cross-origin. Request it with CORS before
// painting it on canvas; otherwise canvas.toDataURL() rejects the PDF export.
const noLogoPaths = new Set(["sin-logo", "__sin_logo__"]);
const hasStoredLogo = (company) => { const path = String(company?.logoPath || "").trim(); return Boolean(path && !noLogoPaths.has(path)); };
const imageFrom = (source) => new Promise((resolve) => { if (!source) return resolve(null); const image = new Image(); let completed = false; const finish = (value) => { if (completed) return; completed = true; clearTimeout(timeout); resolve(value); }; const timeout = setTimeout(() => finish(null), 8000); image.crossOrigin = "anonymous"; image.onload = () => finish(image); image.onerror = () => finish(null); image.src = source; });
const requireStoredLogo = (company, logo) => { if (!logo && hasStoredLogo(company)) throw new Error(`No se pudo cargar el logo de ${company.name}. Vuelva a guardarlo desde Empresas e inténtelo nuevamente.`); };
const drawLogo = async (ctx, company, x, y, color) => { const size = 188; rounded(ctx, x, y, size, size, 16); ctx.fillStyle = color; ctx.fill(); const logo = await imageFrom(company.logoData); requireStoredLogo(company, logo); if (!logo) { text(ctx, initials(company.name), x + size / 2, y + 108, { size: 46, weight: 700, color: darkText(color), align: "center" }); return; } ctx.save(); rounded(ctx, x, y, size, size, 16); ctx.clip(); ctx.fillStyle = "#fff"; ctx.fillRect(x, y, size, size); const scale = Math.min(size / logo.width, size / logo.height); const width = logo.width * scale; const height = logo.height * scale; ctx.drawImage(logo, x + (size - width) / 2, y + (size - height) / 2, width, height); ctx.restore(); };
const drawPayrollLogo = async (ctx, company, x, y, color) => { const width = 245; const height = 200; const logo = await imageFrom(company.logoData); requireStoredLogo(company, logo); if (!logo) { rounded(ctx, x, y, width, height, 18); ctx.fillStyle = color; ctx.fill(); text(ctx, initials(company.name), x + width / 2, y + 118, { size: 56, weight: 700, color: darkText(color), align: "center" }); return; } const scale = Math.min(width / logo.width, height / logo.height); const renderedWidth = logo.width * scale; const renderedHeight = logo.height * scale; ctx.drawImage(logo, x + (width - renderedWidth) / 2, y + (height - renderedHeight) / 2, renderedWidth, renderedHeight); };
const drawCompany = (ctx, company, x, y, color, details = {}) => { const info = [["EMPRESA", company.legalName || company.name], ["RUC", company.ruc], ["DIRECCIÓN", company.address], ["EMAIL", company.email], ["TELÉFONO", company.phone], ...(details.period ? [["PERIODO", details.period]] : [])]; info.forEach(([label, value], index) => { const row = y + index * 26; text(ctx, label, x, row, { size: 17, weight: 700, color: shade(color, .68) }); text(ctx, ":", x + 180, row, { size: 17, color: "#5a554f" }); text(ctx, value, x + 205, row, { size: 17, color: "#292620" }); }); };
const drawSection = (ctx, title, y, color) => { ctx.fillStyle = color; ctx.fillRect(80, y, 1080, 48); text(ctx, title, 98, y + 31, { size: 18, weight: 700, color: darkText(color) }); return y + 48; };
const drawRows = (ctx, rows, y, color, numbered = false, options = {}) => { const left = 80; const width = 1080; const codeX = numbered ? 100 : 100; const conceptX = numbered ? 175 : 215; const amountX = 1135; const height = options.height || 42; const size = options.size || 17; rows.forEach((row, index) => { const textY = y + Math.min(27, height - 9); ctx.fillStyle = index % 2 ? "#fbfaf8" : "#ffffff"; ctx.fillRect(left, y, width, height); line(ctx, left, y + height, left + width, y + height); if (numbered) text(ctx, String(index + 1), codeX, textY, { size }); else text(ctx, row.code || "", codeX, textY, { size: Math.min(16, size), color: shade(color, .68) }); text(ctx, row.concept || row.description || "", conceptX, textY, { size }); text(ctx, money(row.amount), amountX, textY, { size, align: "right" }); y += height; }); return y; };
const footer = (ctx, color) => { line(ctx, 80, 1660, 1160, 1660, color, 2); text(ctx, "Emitido por Estudio Contable JK · Chile, Amarilis 00011 — Huánuco, Perú", 80, 1694, { size: 14, color: "#625b53" }); text(ctx, "contacto@estudiojk.com.pe · 950 361 967", 80, 1720, { size: 14, color: "#625b53" }); };
const payrollSignatures = (ctx, color, y) => { line(ctx, 165, y, 500, y, shade(color, .7)); line(ctx, 740, y, 1075, y, shade(color, .7)); text(ctx, "FIRMA EMPLEADOR", 332, y + 28, { size: 16, weight: 700, color: "#292620", align: "center" }); text(ctx, "FIRMA TRABAJADOR", 908, y + 28, { size: 16, weight: 700, color: "#292620", align: "center" }); };
const canvas = () => { const item = document.createElement("canvas"); item.width = 1240; item.height = 1754; const ctx = item.getContext("2d"); ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, item.width, item.height); return [item, ctx]; };
const base64Bytes = (value) => { const raw = atob(value); const bytes = new Uint8Array(raw.length); for (let index = 0; index < raw.length; index += 1) bytes[index] = raw.charCodeAt(index); return bytes; };
const ascii = (value) => new TextEncoder().encode(value);
const join = (parts) => { const size = parts.reduce((sum, part) => sum + part.length, 0); const result = new Uint8Array(size); let at = 0; parts.forEach((part) => { result.set(part, at); at += part.length; }); return result; };
const pdfFromCanvas = (item) => { const jpeg = base64Bytes(item.toDataURL("image/jpeg", .94).split(",")[1]); const content = "q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ"; const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /Resources << /XObject << /Im0 4 0 R >> >> /MediaBox [0 0 595.28 841.89] /Contents 5 0 R >>", null, `<< /Length ${content.length} >>\nstream\n${content}\nendstream`]; const chunks = [ascii("%PDF-1.4\n%PDF Estudio JK\n")]; const offsets = [0]; let length = chunks[0].length; const add = (data) => { chunks.push(data); length += data.length; };
  objects.forEach((object, index) => { offsets.push(length); add(ascii(`${index + 1} 0 obj\n`)); if (index === 3) { add(ascii(`<< /Type /XObject /Subtype /Image /Width ${item.width} /Height ${item.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`)); add(jpeg); add(ascii("\nendstream\n")); } else add(ascii(`${object}\n`)); add(ascii("endobj\n")); }); const start = length; add(ascii(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`)); return join(chunks); };
const pdfBlob = (item) => new Blob([pdfFromCanvas(item)], { type: "application/pdf" });
const fileName = (value) => `${String(value || "documento").replace(/\.pdf$/i, "").replace(/[\\/:*?"<>|]/g, "-")}.pdf`;
const download = (item, filename) => { const blob = pdfBlob(item); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = fileName(filename); document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1200); return blob; };
const preview = async (createCanvas, title) => { const tab = window.open("", "_blank"); if (!tab) return false; tab.document.title = title; tab.document.body.innerHTML = "<p style=\"font-family:Arial,sans-serif;padding:24px\">Preparando vista previa…</p>"; const url = URL.createObjectURL(pdfBlob(await createCanvas())); tab.location.replace(url); setTimeout(() => URL.revokeObjectURL(url), 60000); return true; };

async function payrollCanvas(company, payroll) {
  const [item, ctx] = canvas(); const color = hex(company.color);
  ctx.fillStyle = color; ctx.fillRect(0, 0, 1240, 16); ctx.fillRect(0, 1738, 1240, 16);
  await drawPayrollLogo(ctx, company, 900, 20, color);
  text(ctx, "BOLETA DE PAGO", 620, 100, { size: 44, weight: 700, color, align: "center" });
  text(ctx, "Trabajador — Reporte individual", 620, 137, { size: 18, color: "#5d564e", align: "center" });
  drawCompany(ctx, company, 80, 292, color, { period: payroll.period }); line(ctx, 80, 455, 1160, 455, color, 2);
  let y = drawSection(ctx, "1. DATOS DEL TRABAJADOR", 490, color);
  const fields = [["Apellidos y nombres", payroll.employee], ["DNI", payroll.dni, "Situación", payroll.status || "ACTIVO"], ["Fecha de ingreso", payroll.startDate, "CUSPP", payroll.cuspp || "-"], ["Tipo de trabajador", payroll.workerType, "Régimen pensionario", payroll.pension], ["Días laborados", payroll.daysWorked || "0", "Días subsidiados", payroll.daysSubsidized || "0"], ["Horas trabajadas", payroll.hoursWorked || payroll.ordinaryHours || "0"]];
  fields.forEach((row, index) => { const height = 46; ctx.fillStyle = index % 2 ? "#fbfaf8" : "#fff"; ctx.fillRect(80, y, 1080, height); line(ctx, 80, y + height, 1160, y + height); text(ctx, row[0], 96, y + 29, { size: 17, weight: 700 }); text(ctx, row[1], 330, y + 29, { size: 17 }); if (row[2]) { line(ctx, 535, y, 535, y + height); text(ctx, row[2], 555, y + 29, { size: 17, weight: 700 }); text(ctx, row[3], 800, y + 29, { size: 17 }); } y += height; });
  y += 16; y = drawSection(ctx, "Cód.        2. Ingresos                                                            Importe S/", y, color); y = drawRows(ctx, payroll.incomes || [], y, color);
  y += 12; y = drawSection(ctx, "Cód.        3. Descuentos del trabajador                            Importe S/", y, color); y = drawRows(ctx, payroll.discounts || [], y, color);
  y += 14; [["Total ingresos", money(payroll.totalIncome)], ["Total descuentos", money(payroll.totalDiscounts)]].forEach(([label, amount]) => { ctx.fillStyle = "#fff"; ctx.fillRect(80, y, 1080, 44); line(ctx, 80, y + 44, 1160, y + 44); text(ctx, label, 98, y + 28, { size: 18, weight: 700, color: "#534e47" }); text(ctx, amount, 1135, y + 28, { size: 18, align: "right" }); y += 44; });
  ctx.fillStyle = color; ctx.fillRect(80, y, 1080, 53); text(ctx, "NETO A PAGAR", 98, y + 34, { size: 20, weight: 700, color: darkText(color) }); text(ctx, money(payroll.net), 1135, y + 34, { size: 20, weight: 700, color: darkText(color), align: "right" });
  y += 86; text(ctx, "Cód.        4. Aportes del empleador (informativo)                 Importe S/", 95, y, { size: 16, weight: 700, color: shade(color, .72) }); const contributionsEnd = drawRows(ctx, payroll.employerContributions || [], y + 16, color, false, { height: 34, size: 16 });
  payrollSignatures(ctx, color, Math.min(1605, Math.max(1575, contributionsEnd + 30))); footer(ctx, color); return item;
}
async function feeCanvas(company, data) { const [item, ctx] = canvas(); const color = hex(company.color); ctx.fillStyle = color; ctx.fillRect(0, 0, 1240, 16); ctx.fillRect(0, 1738, 1240, 16); await drawLogo(ctx, company, 80, 72, color); text(ctx, "RECIBO POR HONORARIOS", 1160, 118, { size: 43, weight: 700, color, align: "right" }); text(ctx, `N.º ${company.ruc.slice(-6)} · ${data.date || new Date().toISOString().slice(0, 10)}`, 1160, 154, { size: 18, color: "#5d564e", align: "right" }); drawCompany(ctx, company, 80, 292, color); line(ctx, 80, 455, 1160, 455, color, 2); text(ctx, "“Año de la Esperanza y el Fortalecimiento de la Democracia”", 620, 492, { size: 18, weight: 700, color: shade(color, .76), align: "center" }); const defaultGreeting = `Sr(a). ${company.representative || "representante"}, representante de ${company.name}: reciba usted el cordial saludo de Estudio Contable JK. Por medio del presente documento nos dirigimos a usted para alcanzarle el detalle de los honorarios profesionales correspondientes a los servicios prestados, agradeciendo de antemano su atención y pronta conformidad.`; let y = paragraph(ctx, data.greeting || defaultGreeting, 80, 540, 1080, { size: 19, color: "#37332e", leading: 29 }); y += 40; y = drawSection(ctx, "N.º        Concepto                                                            Importe S/", y, color); y = drawRows(ctx, data.items || [], y, color, true); y += 20; const total = data.items.reduce((sum, entry) => sum + Number(entry.amount || 0), 0); ctx.fillStyle = color; ctx.fillRect(80, y, 1080, 60); text(ctx, "TOTAL A PAGAR", 105, y + 39, { size: 22, weight: 700, color: darkText(color) }); text(ctx, money(total), 1135, y + 39, { size: 22, weight: 700, color: darkText(color), align: "right" }); if (data.observations) { y += 95; text(ctx, "Observaciones", 80, y, { size: 17, weight: 700, color }); y = paragraph(ctx, data.observations, 80, y + 28, 700, { size: 17, color: "#4d4841" }); } line(ctx, 740, 1470, 1125, 1470, shade(color, .7)); text(ctx, "Firma y sello autorizado", 932, 1500, { size: 16, color: "#625b53", align: "center" }); footer(ctx, color); return item; }

const feeDateLabel = (value) => { const date = new Date(`${value || new Date().toISOString().slice(0, 10)}T00:00:00`); return Number.isNaN(date.getTime()) ? String(value || "") : date.toLocaleDateString("es-PE"); };
const drawFeeStudyLogo = async (ctx, x, y) => { const width = 300; const height = 150; x -= 35; const logo = await imageFrom("/assets/contenido/jk-logo.png"); if (!logo) { text(ctx, "JK ASESORES CONTABLES", x + width / 2, y + 78, { size: 24, weight: 700, color: "#173e67", align: "center" }); return; } const scale = Math.min(width / logo.width, height / logo.height); const renderedWidth = logo.width * scale; const renderedHeight = logo.height * scale; ctx.drawImage(logo, x + (width - renderedWidth) / 2, y + (height - renderedHeight) / 2, renderedWidth, renderedHeight); };
const drawFeePayment = (ctx, y, color) => { const x = 80; const width = 1080; const lines = ["YAPE O PLIN al 950 361 967", "INTERBANK - Cuenta Simple Soles: 562 3282707075", "INTERBANK - CCI: 00356201328270707567", "BCP - Cuenta Soles: 36594826418006", "BCP - CCI: 00236519482641800657"]; const height = 184; ctx.fillStyle = "#f6f8fa"; ctx.fillRect(x, y, width, height); ctx.strokeStyle = shade(color, .72); ctx.lineWidth = 1; ctx.strokeRect(x, y, width, height); text(ctx, "MEDIOS DE PAGO", x + 24, y + 29, { size: 17, weight: 700, color }); lines.forEach((value, index) => text(ctx, value, x + 24, y + 61 + index * 25, { size: 16, color: "#37332e" })); return y + height; };
const drawFeeSignature = async (ctx, color, y) => { const signature = await imageFrom("/assets/contenido/firma-digital-jk.png"); const width = 300; const height = 145; if (signature) { const scale = Math.min(width / signature.width, height / signature.height); const renderedWidth = signature.width * scale; const renderedHeight = signature.height * scale; ctx.drawImage(signature, 932 - renderedWidth / 2, y - renderedHeight - 8, renderedWidth, renderedHeight); } line(ctx, 740, y, 1125, y, shade(color, .7)); text(ctx, "Firma y sello autorizado", 932, y + 28, { size: 16, color: "#625b53", align: "center" }); };
const feeFooter = (ctx, color) => { line(ctx, 80, 1660, 1160, 1660, color, 2); text(ctx, "JK ASESORES CONTABLES · JR. CHILE MZ. A LT. 7 SAN LUIS - AMARILIS-HUANUCO", 80, 1694, { size: 13, color: "#625b53" }); text(ctx, "jk.asesorescontables17@gmail.com · 950 361 967", 80, 1720, { size: 14, color: "#625b53" }); };
async function feeCanvasV2(company, data) { const [item, ctx] = canvas(); const color = hex(company.color); ctx.fillStyle = color; ctx.fillRect(0, 0, 1240, 16); ctx.fillRect(0, 1738, 1240, 16); await drawFeeStudyLogo(ctx, 80, 46); text(ctx, "RECIBO POR HONORARIOS", 620, 116, { size: 43, weight: 700, color, align: "center" }); text(ctx, `N.º ${data.number || data.feeNumber || 100}`, 620, 158, { size: 17, color: "#5d564e", align: "center" }); text(ctx, `Fecha de emisión: ${feeDateLabel(data.date)}`, 620, 184, { size: 17, color: "#5d564e", align: "center" }); drawCompany(ctx, company, 80, 292, color); line(ctx, 80, 455, 1160, 455, color, 2); text(ctx, "“Año de la Esperanza y el Fortalecimiento de la Democracia”", 620, 492, { size: 18, weight: 700, color: shade(color, .76), align: "center" }); const defaultGreeting = `Sr(a). ${company.representative || "representante"}, representante de ${company.name}: reciba usted el cordial saludo de JK Asesores Contables. Por medio del presente documento nos dirigimos a usted para alcanzarle el detalle de los honorarios profesionales correspondientes a los servicios prestados, agradeciendo de antemano su atención y pronta conformidad.`; let y = paragraph(ctx, data.greeting || defaultGreeting, 80, 540, 1080, { size: 19, color: "#37332e", leading: 29 }); y += 40; y = drawSection(ctx, "N.º        Concepto                                                            Importe S/", y, color); y = drawRows(ctx, data.items || [], y, color, true); y += 20; const total = (data.items || []).reduce((sum, entry) => sum + Number(entry.amount || 0), 0); ctx.fillStyle = color; ctx.fillRect(80, y, 1080, 60); text(ctx, "TOTAL A PAGAR", 105, y + 39, { size: 22, weight: 700, color: darkText(color) }); text(ctx, money(total), 1135, y + 39, { size: 22, weight: 700, color: darkText(color), align: "right" }); y = drawFeePayment(ctx, y + 24, color) + 28; if (data.observations) { text(ctx, "Observaciones", 80, y, { size: 17, weight: 700, color }); y = paragraph(ctx, data.observations, 80, y + 28, 1080, { size: 17, color: "#4d4841", leading: 24 }) + 18; } await drawFeeSignature(ctx, color, Math.min(1580, Math.max(1460, y + 42))); feeFooter(ctx, color); return item; }
export async function downloadPayrollPdf(company, payroll, filename = `Boleta-${payroll.period}`) { return download(await payrollCanvas(company, payroll), filename); }
export async function downloadFeePdf(company, data, filename = `Honorarios-${company.ruc}`) { return download(await feeCanvasV2(company, data), filename); }
export function previewPayrollPdf(company, payroll, filename = `Boleta-${payroll.period}`) { return preview(() => payrollCanvas(company, payroll), fileName(filename)); }
export function previewFeePdf(company, data, filename = `Honorarios-${company.ruc}`) { return preview(() => feeCanvasV2(company, data), fileName(filename)); }
export function payrollDocument(company, payroll) { return `<article style="font-family:Arial,sans-serif;padding:32px;color:#201d19"><h1 style="color:${esc(hex(company.color))}">Boleta de pago · ${esc(payroll.period)}</h1><p><b>${esc(company.name)}</b> · RUC ${esc(company.ruc)}</p><p>Trabajador: ${esc(payroll.employee)} · Neto: ${money(payroll.net)}</p><p>Use Descargar PDF para obtener el archivo con diseño institucional, logo y color corporativo.</p></article>`; }
export function feeDocument(company, data) { const total = data.items.reduce((sum, item) => sum + Number(item.amount || 0), 0); return `<article style="font-family:Arial,sans-serif;padding:32px;color:#201d19"><h1 style="color:${esc(hex(company.color))}">Recibo por honorarios</h1><p><b>${esc(company.name)}</b> · RUC ${esc(company.ruc)}</p><p>Total: ${money(total)}</p><p>Use Descargar PDF para obtener el archivo con diseño institucional, logo y color corporativo.</p></article>`; }
export function openPrint(html, filename) { const win = window.open("", "_blank", "width=900,height=900"); if (!win) return false; win.document.write(html); win.document.close(); win.document.title = filename; setTimeout(() => win.print(), 250); return true; }
export { money };
