"use client";

import { FormEvent, useState } from "react";
import { AuthSession, auth } from "../lib/auth";

export function AuthScreen({ mode, onSuccess, onBack, onSwitch }: { mode: "login" | "register"; onSuccess: (session: AuthSession) => void; onBack: () => void; onSwitch: (mode: "login" | "register") => void }) {
  const isRegister = mode === "register";
  const [name, setName] = useState(""); const [company, setCompany] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); const result = isRegister ? auth.register({ name, email, password, company }) : auth.signIn(email, password); setBusy(false); if (result.error || !result.session) { setError(result.error ?? "No se pudo iniciar sesión."); return; } onSuccess(result.session); };
  return <div className="auth-shell"><div className="auth-visual"><div className="auth-visual-overlay"/><button className="auth-back" onClick={onBack}>← Volver al sitio</button><div className="auth-visual-copy"><span className="hero-kicker">✣ ESTUDIO CONTABLE PREMIUM</span><h1>La tranquilidad de tener sus números en buenas manos.</h1><p>Acceda a su espacio de trabajo seguro y mantenga sus documentos al alcance.</p></div><span className="auth-visual-sign">ESTUDIO JK · CONTABLE · TRIBUTARIO</span></div><div className="auth-panel"><div className="auth-brand"><span className="public-brand-mark">JK</span><div><b>Estudio JK</b><small>CONTABILIDAD CON PROPÓSITO</small></div></div><div className="auth-heading"><span className="public-eyebrow">{isRegister ? "NUEVO CLIENTE" : "ÁREA PRIVADA"}</span><h2>{isRegister ? "Cree su cuenta" : "Bienvenido de nuevo"}</h2><p>{isRegister ? "Regístrese para solicitar asesoría y acceder a sus documentos." : "Ingrese sus credenciales para acceder a su espacio de trabajo."}</p></div><form onSubmit={submit} className="auth-form">{isRegister && <><label>Nombre completo<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Su nombre" /></label><label>Empresa<input required value={company} onChange={(event) => setCompany(event.target.value)} placeholder="Razón social" /></label></>}<label>Correo electrónico<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="nombre@empresa.com" /></label><label>Contraseña<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={isRegister ? "Mínimo 6 caracteres" : "Su contraseña"} /></label>{!isRegister && <div className="auth-options"><label className="check-label"><input type="checkbox" /> Recordarme</label><button type="button">¿Olvidó su contraseña?</button></div>}{error && <div className="auth-error">{error}</div>}<button className="gold-button auth-submit" disabled={busy}>{busy ? "Procesando..." : isRegister ? "Crear cuenta" : "Iniciar sesión"} <span>→</span></button></form>{!isRegister && <div className="demo-access"><b>Acceso administrador local</b><span>admin@estudiojk.com.pe · contraseña: 12345</span></div>}<p className="auth-switch">{isRegister ? "¿Ya tiene una cuenta?" : "¿Aún no tiene una cuenta?"} <button onClick={() => onSwitch(isRegister ? "login" : "register")}>{isRegister ? "Iniciar sesión" : "Registrarse"}</button></p><small className="auth-legal">Al continuar acepta nuestros términos de servicio y política de privacidad.</small></div></div>;
}
