"use client";

import { AuthSession } from "../lib/auth";
import { Company, GeneratedDocument } from "../lib/types";

export function ClientPortal({ session, documents, companies, onLogout }: { session: AuthSession; documents: GeneratedDocument[]; companies: Company[]; onLogout: () => void }) {
  const company = companies.find((item) => item.name.toLowerCase().includes((session.company ?? "").toLowerCase())) ?? companies[0];
  return <div className="client-portal"><header className="client-nav"><div className="public-brand"><span className="public-brand-mark">JK</span><span><b>Estudio JK</b><small>ESPACIO DEL CLIENTE</small></span></div><div className="client-user"><span>{session.name.slice(0, 1).toUpperCase()}</span><div><b>{session.name}</b><small>{session.email}</small></div><button onClick={onLogout}>Salir</button></div></header><main className="client-main"><div className="client-welcome"><span className="public-eyebrow">ESPACIO DEL CLIENTE</span><h1>Hola, {session.name.split(" ")[0]}.</h1><p>Su información y documentos, ordenados y disponibles cuando los necesite.</p></div><div className="client-grid"><section className="client-card client-company"><span className="service-icon">▥</span><small>EMPRESA ASOCIADA</small><h2>{company?.name ?? session.company ?? "Su empresa"}</h2><p>{company?.ruc ? `RUC ${company.ruc}` : "Estamos terminando de configurar su espacio."}</p><button className="arrow-link">Ver información <span>→</span></button></section><section className="client-card"><div className="client-card-heading"><div><small>DOCUMENTOS RECIENTES</small><h2>{documents.length} archivos</h2></div><span className="service-icon">◫</span></div>{documents.slice(0, 3).map((document) => <div className="client-document" key={document.id}><span>{document.type === "boleta" ? "B" : "H"}</span><div><b>{document.title}</b><small>{document.companyName}</small></div><button>↓</button></div>)}{documents.length === 0 && <p className="empty-state">Su asesor cargará aquí los documentos generados.</p>}</section></div><section className="client-help"><div><span className="public-eyebrow">¿NECESITA AYUDA?</span><h2>Estamos para acompañarlo.</h2><p>Comuníquese con nuestro equipo para solicitar información o asistencia.</p></div><a className="gold-button" href="https://wa.me/51950361967" target="_blank" rel="noreferrer">Contactar al estudio →</a></section></main></div>;
}
