import { Company, GeneratedDocument } from "../lib/types";

function relativeDate(date: string) { const days = Math.floor((Date.now() - new Date(date).getTime()) / 86400000); return days <= 0 ? "hoy" : days === 1 ? "ayer" : `hace ${days} días`; }

export function Dashboard({ companies, documents, onNavigate }: { companies: Company[]; documents: GeneratedDocument[]; onNavigate: (view: "companies" | "templates" | "fees" | "history") => void }) {
  const active = companies.filter((company) => company.active).length;
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">RESUMEN OPERATIVO</span><h1>Dashboard</h1><p>Una vista clara del estudio, sus empresas y archivos generados.</p></div><button className="gold-button" onClick={() => onNavigate("templates")}>＋ Nueva generación</button></div><div className="metrics"><button className="metric-card" onClick={() => onNavigate("companies")}><span className="metric-icon">▥</span><strong>{active}<small> / {companies.length}</small></strong><span>EMPRESAS ACTIVAS</span><i>↗</i></button><button className="metric-card"><span className="metric-icon">♙</span><strong>1</strong><span>USUARIOS REGISTRADOS</span><i>↗</i></button><button className="metric-card" onClick={() => onNavigate("history")}><span className="metric-icon">◫</span><strong>{documents.length}</strong><span>DOCUMENTOS GENERADOS</span><i>↗</i></button><button className="metric-card"><span className="metric-icon">⌁</span><strong>{documents.length ? 3 : 0}</strong><span>ACTIVIDAD RECIENTE</span><i>↗</i></button></div><div className="dashboard-grid"><section className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">TRAZABILIDAD</span><h2>Actividad reciente</h2></div><button className="text-button" onClick={() => onNavigate("history")}>Ver historial →</button></div>{documents.length === 0 ? <div className="empty-state">Aún no hay documentos generados.</div> : <div className="activity-list">{documents.slice(0, 5).map((doc) => <button className="activity-row" key={doc.id} onClick={() => onNavigate("history")}><span className={`file-icon ${doc.type}`}>{doc.type === "boleta" ? "B" : "H"}</span><span><b>{doc.title}</b><small>{doc.companyName} · {doc.type === "boleta" ? "Boleta" : "Honorarios"}</small></span><time>{relativeDate(doc.createdAt)}</time><span className="row-arrow">→</span></button>)}</div>}</section><section className="panel quick-panel"><span className="eyebrow">ACCESOS RÁPIDOS</span><h2>Continúa tu trabajo</h2><button className="quick-action" onClick={() => onNavigate("templates")}><span>↥</span><div><b>Generar boleta PLAME</b><small>Sube un XML de SUNAT y descarga el PDF</small></div><i>→</i></button><button className="quick-action" onClick={() => onNavigate("fees")}><span>▣</span><div><b>Generar honorarios</b><small>Crea un recibo con múltiples conceptos</small></div><i>→</i></button><button className="quick-action" onClick={() => onNavigate("companies")}><span>＋</span><div><b>Registrar empresa</b><small>Guarda identidad, logo y contactos</small></div><i>→</i></button></section></div></div>;
}

