import { ChangeEvent, useState } from "react";
import { Company, GeneratedDocument, XmlPayroll } from "../lib/types";
import { parseSunatXml } from "../lib/xml-parser";
import { renderPayrollDocument, openPrintableDocument } from "../lib/document-renderer";
import { DocumentPreview } from "./DocumentPreview";

export function TemplateGenerator({ companies, onGenerated }: { companies: Company[]; onGenerated: (document: GeneratedDocument) => void }) {
  const [fileName, setFileName] = useState(""); const [payroll, setPayroll] = useState<XmlPayroll | null>(null); const [companyId, setCompanyId] = useState(""); const [error, setError] = useState(""); const [preview, setPreview] = useState(false); const company = companies.find((item) => item.id === companyId) ?? null;
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(""); setFileName(file.name); const reader = new FileReader(); reader.onload = () => { try { setPayroll(parseSunatXml(String(reader.result))); } catch (e) { setPayroll(null); setError(e instanceof Error ? e.message : "No se pudo leer el XML."); } }; reader.readAsText(file); };
  const download = () => { if (!payroll || !company) return; const html = renderPayrollDocument(company, payroll); openPrintableDocument(html, `Boleta-${payroll.period}-${payroll.dni}`); onGenerated({ id: `doc-${Date.now()}`, type: "boleta", title: `Boleta de pago · ${payroll.period}`, companyId: company.id, companyName: company.name, period: payroll.period, amount: payroll.net, createdAt: new Date().toISOString(), payload: { payroll } }); };
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">AUTOMATIZACIÓN · PLAME R08</span><h1>Generar plantillas</h1><p>Sube un XML exportado desde SUNAT y crea una boleta profesional con la identidad de la empresa.</p></div><span className="ready-badge"><i/> Motor reutilizable activo</span></div><div className="generator-layout"><section className="panel generator-card"><div className="step-heading"><span>1</span><div><h2>Cargar XML de SUNAT</h2><p>Leemos la hoja real <b>SUNAT-PDT</b> sin asumir campos.</p></div></div><label className={`dropzone ${payroll ? "has-file" : ""}`}><input type="file" accept=".xml,text/xml" onChange={upload} />{payroll ? <><span className="success-icon">✓</span><b>{fileName}</b><small>XML procesado correctamente · {payroll.employee}</small></> : <><span className="upload-icon">↥</span><b>Haz clic para subir o arrastra el archivo</b><small>Formato .xml · PLAME R08</small></>}</label>{error && <div className="inline-error">{error}</div>}{payroll && <div className="parsed-summary"><span><b>RUC</b>{payroll.ruc}</span><span><b>Periodo</b>{payroll.period}</span><span><b>Ingresos</b>{payroll.incomes.length}</span><span><b>Neto</b>S/ {payroll.net.toFixed(2)}</span></div>}</section><section className="panel generator-card"><div className="step-heading"><span>2</span><div><h2>Seleccionar empresa</h2><p>El logo y los datos saldrán de la empresa elegida.</p></div></div><label>Empresa emisora<select value={companyId} onChange={(e) => setCompanyId(e.target.value)}><option value="">Selecciona una empresa…</option>{companies.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.ruc}</option>)}</select></label>{company && <div className="selected-company"><span className="company-avatar" style={{ background: company.color }}>{company.logoData ? <img src={company.logoData} alt="" /> : company.name.slice(0, 2)}</span><span><b>{company.name}</b><small>{company.address} · {company.phone}</small></span><span className="check">✓</span></div>}<div className="document-fields"><span><b>Incluye</b>Trabajador, régimen, conceptos, ingresos, descuentos, aportes y neto.</span><span><b>Identidad</b>Logo, dirección, teléfono y correo de la empresa.</span></div></section></div><div className="generator-actions"><button className="secondary-button" disabled={!payroll || !company} onClick={() => setPreview(true)}>◉ Vista previa</button><button className="gold-button" disabled={!payroll || !company} onClick={download}>↓ Descargar PDF</button><button className="text-button" onClick={() => { setPayroll(null); setFileName(""); setCompanyId(""); setError(""); }}>↻ Reiniciar</button>{(!payroll || !company) && <span className="action-hint">Sube un XML y selecciona una empresa para habilitar las acciones.</span>}</div>{preview && payroll && company && <DocumentPreview company={company} payroll={payroll} onClose={() => setPreview(false)} />}</div>;
}

