import { Company, GeneratedDocument, XmlPayroll } from "./types";

export const sampleCompanies: Company[] = [
  {
    id: "company-chavez",
    name: "CORPORACIÓN CHÁVEZ E.I.R.L.",
    legalName: "CORPORACIÓN CHÁVEZ EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA",
    ruc: "20489725437",
    address: "Av. Los Álamos 234, Trujillo",
    district: "Trujillo",
    province: "Trujillo",
    department: "La Libertad",
    phone: "+51 944 123 456",
    email: "contacto@chavez.pe",
    representative: "Ronald Chávez",
    color: "#9a7627",
    active: true,
    createdAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "company-andinas",
    name: "INVERSIONES ANDINAS S.A.C.",
    legalName: "INVERSIONES ANDINAS SOCIEDAD ANÓNIMA CERRADA",
    ruc: "20512345678",
    address: "Av. Javier Prado 456, Lima",
    district: "San Isidro",
    province: "Lima",
    department: "Lima",
    phone: "+51 988 555 111",
    email: "gerencia@andinas.pe",
    representative: "María Torres",
    color: "#273247",
    active: true,
    createdAt: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "company-pacifico",
    name: "SERVICIOS INTEGRALES PACÍFICO S.R.L.",
    legalName: "SERVICIOS INTEGRALES PACÍFICO SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA",
    ruc: "20609988776",
    address: "Jr. Los Cedros 180, Huánuco",
    district: "Huánuco",
    province: "Huánuco",
    department: "Huánuco",
    phone: "+51 962 345 678",
    email: "info@pacifico.pe",
    representative: "Luis Fernández",
    color: "#8f3515",
    active: false,
    createdAt: "2026-06-20T09:00:00.000Z",
  },
];

export const samplePayroll: XmlPayroll = {
  employer: "CORPORACIÓN CHÁVEZ EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA",
  ruc: "20489725437",
  period: "06/2026",
  employee: "RONALD RUBEN CHAVEZ CALDERON",
  dni: "40654524",
  status: "ACTIVO O SUBSIDIADO",
  startDate: "01/02/2013",
  workerType: "EJECUTIVO",
  pension: "SPP HORIZONTE",
  cuspp: "594681RCCVD1",
  daysWorked: "30",
  daysSubsidized: "0",
  condition: "Domiciliado",
  ordinaryHours: "200",
  incomes: [
    { code: "0121", concept: "REMUNERACIÓN O JORNAL BÁSICO", amount: 1387 },
    { code: "0201", concept: "ASIGNACIÓN FAMILIAR", amount: 113 },
  ],
  discounts: [
    { code: "0601", concept: "COMISIÓN AFP PORCENTUAL", amount: 23.25 },
    { code: "0605", concept: "RENTA QUINTA CATEGORÍA RETENCIONES", amount: 0 },
    { code: "0606", concept: "PRIMA DE SEGURO AFP", amount: 20.55 },
    { code: "0608", concept: "SPP - APORTACIÓN OBLIGATORIA", amount: 150 },
  ],
  employerContributions: [{ code: "0804", concept: "ESSALUD (REGULAR CBSSP AGRAR/AC) TRAB", amount: 135 }],
  totalIncome: 1500,
  totalDiscounts: 193.8,
  net: 1306.2,
};

export const sampleDocuments: GeneratedDocument[] = [
  {
    id: "doc-1",
    type: "boleta",
    title: "Boleta de pago · 06/2026",
    companyId: "company-chavez",
    companyName: "CORPORACIÓN CHÁVEZ E.I.R.L.",
    period: "06/2026",
    amount: 1306.2,
    createdAt: "2026-08-03T14:20:00.000Z",
    payload: { payroll: samplePayroll },
  },
  {
    id: "doc-2",
    type: "honorarios",
    title: "Honorarios · Pagos servicios contables",
    companyId: "company-andinas",
    companyName: "INVERSIONES ANDINAS S.A.C.",
    amount: 1500,
    createdAt: "2026-07-17T12:30:00.000Z",
    payload: { date: "2026-08-03", greeting: "", observations: "", items: [{ id: "1", description: "pago servicios", amount: 1500 }] },
  },
];

